export const IN_PROGRESS = 'IN_PROGRESS';

export const SCORES_FETCHED = 'SCORES_FETCHED';
export const SCORES_FETCH_FAIL = 'SCORES_FETCH_FAIL';

export const SCORE_CREATED = 'SCORE_CREATED';
export const CREATE_SCORE_FAIL = 'CREATE_SCORE_FAIL';

export const SCORE_UPDATED = 'SCORE_UPDATED';
export const SCORE_UPDATE_FAIL = 'SCORE_UPDATE_FAIL';

export const SCORE_DELETED = 'SCORE_DELETED';
export const SCORE_DELETE_FAIL = 'SCORE_DELETE_FAIL';

export const TURN_OFF_NOTIFY = 'TURN_OFF_NOTIFY';